# Generated by Django 3.2.5 on 2021-07-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(default='dipu.jpg', upload_to='product_images'),
        ),
    ]
