# Generated by Django 3.2.5 on 2021-07-26 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_productmodel_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductModel',
            new_name='Product',
        ),
    ]
